### PR TITLE
remove invalid link for TODO

### PR DESCRIPTION
**Pull request by guliangliangatpingcap**
close https://github.com/tikv/client-java/issues/69

### CODE REVIEW

**Comment by Renkai** [comment]
So is this project still under construction or it is ready for public to use?

**Comment by guliangliangatpingcap** [comment]
hi @Renkai you can use this project at this moment, but it will be reconstructed soon.

**Comment by Renkai** [comment]
@guliangliangatpingcap is there a road map for the reconstructed java-client

**Comment by guliangliangatpingcap** [comment]
> @guliangliangatpingcap is there a road map for the reconstructed java-client

there is a open-source tikv-java-client in tispark project ( https://github.com/pingcap/tispark/tree/master/tikv-client ).

we are going to merge these two clients (probably using tikv-client in tispark) and we will do this job next year.

**Pull request merged**
