### PR TITLE
[to #526] Add codecov on Github Action (#524)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #524 to release-3.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In client-java repo:
git pr https://github.com/tikv/client-java/pull/533
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/client-java.git pr/533:release-3.1-49476d7fa0db
```

---

Signed-off-by: andylokandy <andylokandy@hotmail.com>

Ref #526

### What is changed and how it works?

Add CI using Github Action. Intended to replace jenkins.

### Code changes

- No code

### Check List for Tests

- No code

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
@andylokandy please resolve conflicts.

**Comment by andylokandy** [comment]
@marsishandsome @zz-jason PTAL

**Review by marsishandsome — APPROVED** [review]
LGTM

**Comment by andylokandy** [comment]
@marsishandsome We have to forcibly merge it.

**Pull request merged**
