### PR TITLE
[close #375] warm up RawKVClient while creating it

### LINKED ISSUE #375: the first requests is very slow in RawKVClient
**Is your feature request related to a problem? Please describe.**

The first request 

```json
{
    "start":"17:45:35.667",
    "end":"17:45:35.720",
    "duration":"53ms",
    "func":"get",
    "region":"{Region[8590814505] ConfVer[7164] Version[165] Store[8589948024] KeyRange[xxxxx]:[xxxxx]}",
    "key":"xxxxx",
    "spans":[
        {
            "name":"getRegionByKey",
            "start":"17:45:35.713",
            "end":"17:45:35.715",
            "duration":"2ms"
        },
        {
            "name":"callWithRetry pdpb.PD/GetRegion",
            "start":"17:45:35.713",
            "end":"17:45:35.715",
            "duration":"2ms"
        },
        {
            "name":"gRPC pdpb.PD/GetRegion",
            "start":"17:45:35.713",
            "end":"17:45:35.715",
            "duration":"2ms"
        },
        {
            "name":"callWithRetry tikvpb.Tikv/RawGet",
            "start":"17:45:35.716",
            "end":"17:45:35.720",
            "duration":"4ms"
        },
        {
            "name":"gRPC tikvpb.Tikv/RawGet",
            "start":"17:45:35.716",
            "end":"17:45:35.720",
            "duration":"4ms"
        }
    ]
}
```
**Describe the solution you'd like**

make them fast as the client is running for a long time

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve? 

We find some initialization work that needs to do in the first gRPC call in `RawKVClient` which might result in a timeout in the first few gRPC calls.

First run:

image

Second run:

image

### What is changed and how it works?
To solve this problem, we may launch a `raw_get` request to warm up the runtime.

### Check List 

Tests 

 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Comment by birdstorm** [comment]
IMHO not suitable to warm up the client by calling `get()` when initializing.

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by marsishandsome — APPROVED** [review]
LGTM

**Pull request merged**
