### PR TITLE
Simplified conditions, updated variable to final wherever applicable and removed unreachable throws Exception

### PR DESCRIPTION
**Pull request by rahilsh**
### What problem does this PR solve?
Simplified conditions, updated variable to final wherever applicable and removed unreachable throws Exception

### What is changed and how it works?
Just refactoring and no functional impact

### Check List

Tests

 - Unit test

### CODE REVIEW

**Comment by marsishandsome** [comment]
please run `mvn clean package -DskipTests` and the code will be formateed.

**Comment by rahilsh** [comment]
@marsishandsome Done

**Comment by marsishandsome** [comment]
@rahilsh please add DCO
image

**Comment by rahilsh** [comment]
@marsishandsome Done

**Comment by rahilsh** [comment]
@marsishandsome Please review

**Review by marsishandsome — APPROVED** [review]
LGTM

**Comment by rahilsh** [comment]
Thanks @marsishandsome

**Pull request merged**
