### PR TITLE
fix byte array overflow

### PR DESCRIPTION
**Pull request by ab111404212**
fix byte array overflow when column id greater than 128

### What problem does this PR solve?
 when use tidb-cdc in flink,if table column size greater than 128 fields,the left field value cant't be read,and is null value,after review related code,i found a bug, when column id greater than 128,colIds is overflow,so binary search can't find correct column id in colIDs array

the detail bug description
https://github.com/ververica/flink-cdc-connectors/issues/1883

### CODE REVIEW

**Comment by ab111404212** [comment]
> fix byte array overflow when column id greater than 128
> 
> ### What problem does this PR solve?
> when column id greater than 128,binary search can't find column id in colIDs array

@guliangliangatpingcap @birdstorm please help me with review the code

**Review by birdstorm — DISMISSED** [review]
LGTM

**Comment by ab111404212** [comment]
@birdstorm  amend commit information,please  review again

**Review by birdstorm — APPROVED** [review]
LGTM

**Comment by shiyuhang0** [comment]
Please add a test if it is convenient

**Review by shiyuhang0 — APPROVED** [review]

**Comment by shiyuhang0** [comment]
Fix DCO please

**Review by zhangyangyu — APPROVED** [review]

**Comment by zhangyangyu** [comment]
@ab111404212 could you fix the DCO check?

**Comment by shiyuhang0** [comment]
Your signoff can not match your GitHub mail causing the DCO fail.
img_v2_6502bac6-c5c8-4b83-8429-14e9c084619g

We will reopen a new PR the same as yours

**Comment by shiyuhang0** [comment]
closed by https://github.com/tikv/client-java/pull/728

**Pull request closed without merging**
