### PR TITLE
do not use TiSession.getInstance

### PR DESCRIPTION
**Pull request by marsishandsome**

### CODE REVIEW

**Review by sunxiaoguang — COMMENTED** [review]
Maybe we can eliminate TiSession::getInstance so that people will never have chance to use it wrong.

**Comment by marsishandsome** [comment]
> Maybe we can eliminate TiSession::getInstance so that people will never have chance to use it wrong.

`TiSession::getInstance` is delete from document. I prefer to keep it for the case of compatibility.

**Comment by sunxiaoguang** [comment]
> > Maybe we can eliminate TiSession::getInstance so that people will never have chance to use it wrong.
> 
> `TiSession::getInstance` is delete from document. I prefer to keep it for the case of compatibility.

Sure, let's annotate it as deprecated so we can eventually remove it in the future.

**Review by birdstorm — APPROVED** [review]
LGTM

**Comment by sunxiaoguang** [comment]
LGTM

**Review by sunxiaoguang — APPROVED** [review]

**Pull request merged**
