### PR TITLE
[DNM] fix TLS: ALPN unsupported

### PR DESCRIPTION
**Pull request by marsishandsome**
Signed-off-by: marsishandsome <marsishandsome@gmail.com>

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Comment by ankita25** [comment]
when will this be merged ?

**Comment by marsishandsome** [comment]
> when will this be merged ?

It will be merged until a better fix is found.

**Comment by ankita25** [comment]
Can we get a timeline on when will it be merged ?

**Comment by zz-jason** [comment]
@ankita25 I created a feature request for it. could you describe more details about your use cases and the problems you met?

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. Feel free to reopen it if you wish to advance it in the future.

**Pull request closed without merging**
